name: GameCI Template 🎮

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PW }}

jobs:
  checkLicense:
    name: Check for the Unity license ☑️
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ☠️
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1
        
  buildWebGL:
    name: Build WebGL&Release Github
    runs-on: ubuntu-latest
    steps:
      - name: Build WebGL and Store on Build folder
        uses: game-ci/unity-builder@v4
        with:
          targetPlayform: WebGL
        uses: actions/upload-artifact@v3
        with:
          name: Build-WebGL
          path: build/WebGL
